site_name: FloodsAndHealthTool
site_url: 
site_description: Project documentation for FloodsAndHealthTool.
site_author: Deltares

repo_url: 
edit_uri: blob/master/docs/
### Site metadata ###

site_name: FloodsAndHealthTool
site_description: A Python tool for flood impacts on human health
site_url: https://https://deltares.github.io/FloodsAndHealthTool/

repo_url: https://github.com/Deltares/FloodsAndHealthTool/
edit_uri: docs


### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - Quick start: 1_quick_start.md
  - Introduction: overview_floodshealth.md
  



